export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const REMOVE_ONE_CART_ITEM = 'REMOVE_ONE_CART_ITEM'
export const CLEAR_CART = 'CLEAR_CART'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_CART = 'FETCH_CART'
export const FETCH_PRODUCT_BY_ID = 'FETCH_PRODUCT_BY_ID'
